# Generated by Django 4.2 on 2023-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tc',
            options={'verbose_name': 'Add TC', 'verbose_name_plural': 'Add TC'},
        ),
        migrations.AlterField(
            model_name='member_list',
            name='designation',
            field=models.CharField(choices=[('APrincipal', 'Principal'), ('BPGT (Physics)', 'PGT (Physics)'), ('BPGT (Chemistry)', 'PGT (Chemistry)'), ('BPGT (Maths)', 'BPGT (Maths)'), ('BPGT (Biology)', 'PGT (Biology)'), ('BPGT (Computer)', 'PGT (Computer)'), ('BPGT (Economics)', 'BPGT (Economics)'), ('BPGT (Commerce)', 'PGT (Commerce)'), ('BPGT (English)', 'PGT (English)'), ('BPGT (Hindi)', 'PGT (Hindi)'), ('CTGT (Science)', 'TGT (Science)'), ('CTGT (Maths)', 'TGT (Maths)'), ('CTGT (Sanskrit)', 'TGT (Sanskrit)'), ('CTGT (Social Science)', 'TGT (Social Science)'), ('CTGT (English)', 'TGT (English)'), ('CTGT (Hindi)', 'TGT (Hindi)'), ('DPRT', 'PRT'), ('ESSA', 'SSA'), ('FLab Attendant', 'Lab Attendant'), ('GSub Staff', 'Sub Staff'), ('HJR. Secratariat Assistant', 'JR. Secratariat Assistant')], max_length=32),
        ),
        migrations.AlterField(
            model_name='member_list',
            name='image',
            field=models.ImageField(blank=True, default='website/images/PFP.jpg', null=True, upload_to='website/images/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacant_designation',
            field=models.CharField(choices=[('APrincipal', 'Principal'), ('BPGT (Physics)', 'PGT (Physics)'), ('BPGT (Chemistry)', 'PGT (Chemistry)'), ('BPGT (Maths)', 'BPGT (Maths)'), ('BPGT (Biology)', 'PGT (Biology)'), ('BPGT (Computer)', 'PGT (Computer)'), ('BPGT (Economics)', 'BPGT (Economics)'), ('BPGT (Commerce)', 'PGT (Commerce)'), ('BPGT (English)', 'PGT (English)'), ('BPGT (Hindi)', 'PGT (Hindi)'), ('CTGT (Science)', 'TGT (Science)'), ('CTGT (Maths)', 'TGT (Maths)'), ('CTGT (Sanskrit)', 'TGT (Sanskrit)'), ('CTGT (Social Science)', 'TGT (Social Science)'), ('CTGT (English)', 'TGT (English)'), ('CTGT (Hindi)', 'TGT (Hindi)'), ('DPRT', 'PRT'), ('ESSA', 'SSA'), ('FLab Attendant', 'Lab Attendant'), ('GSub Staff', 'Sub Staff'), ('HJR. Secratariat Assistant', 'JR. Secratariat Assistant')], max_length=32),
        ),
    ]
