# Generated by Django 4.2 on 2023-07-20 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_tc_options_alter_member_list_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 20)),
        ),
        migrations.AlterField(
            model_name='member_list',
            name='designation',
            field=models.CharField(choices=[('APrincipal', 'Principal'), ('BPGT (Physics)', 'PGT (Physics)'), ('BPGT (Chemistry)', 'PGT (Chemistry)'), ('BPGT (Maths)', 'PGT (Maths)'), ('BPGT (Biology)', 'PGT (Biology)'), ('BPGT (Computer)', 'PGT (Computer)'), ('BPGT (Economics)', 'PGT (Economics)'), ('BPGT (Commerce)', 'PGT (Commerce)'), ('BPGT (English)', 'PGT (English)'), ('BPGT (Hindi)', 'PGT (Hindi)'), ('CTGT (Science)', 'TGT (Science)'), ('CTGT (Maths)', 'TGT (Maths)'), ('CTGT (Sanskrit)', 'TGT (Sanskrit)'), ('CTGT (Social Science)', 'TGT (Social Science)'), ('CTGT (English)', 'TGT (English)'), ('CTGT (Hindi)', 'TGT (Hindi)'), ('DPRT', 'PRT'), ('ESSA', 'SSA'), ('FLab Attendant', 'Lab Attendant'), ('GSub Staff', 'Sub Staff'), ('HJR. Secratariat Assistant', 'JR. Secratariat Assistant')], max_length=32),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacant_designation',
            field=models.CharField(choices=[('APrincipal', 'Principal'), ('BPGT (Physics)', 'PGT (Physics)'), ('BPGT (Chemistry)', 'PGT (Chemistry)'), ('BPGT (Maths)', 'PGT (Maths)'), ('BPGT (Biology)', 'PGT (Biology)'), ('BPGT (Computer)', 'PGT (Computer)'), ('BPGT (Economics)', 'PGT (Economics)'), ('BPGT (Commerce)', 'PGT (Commerce)'), ('BPGT (English)', 'PGT (English)'), ('BPGT (Hindi)', 'PGT (Hindi)'), ('CTGT (Science)', 'TGT (Science)'), ('CTGT (Maths)', 'TGT (Maths)'), ('CTGT (Sanskrit)', 'TGT (Sanskrit)'), ('CTGT (Social Science)', 'TGT (Social Science)'), ('CTGT (English)', 'TGT (English)'), ('CTGT (Hindi)', 'TGT (Hindi)'), ('DPRT', 'PRT'), ('ESSA', 'SSA'), ('FLab Attendant', 'Lab Attendant'), ('GSub Staff', 'Sub Staff'), ('HJR. Secratariat Assistant', 'JR. Secratariat Assistant')], max_length=32),
        ),
    ]
