# Generated by Django 4.2.4 on 2023-08-05 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_notice_date_alter_member_list_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 5)),
        ),
    ]
