# Generated by Django 4.2.4 on 2023-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='principals_message',
            name='name',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
