# Generated by Django 4.2.4 on 2023-08-10 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_principals_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_list',
            name='image',
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 10)),
        ),
    ]
