# Generated by Django 4.2.4 on 2023-08-23 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_member_list_image_alter_notice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Affiliation Report',
                'verbose_name_plural': 'Add Affiliation Report',
            },
        ),
        migrations.CreateModel(
            name='Calender_of_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Calender Activity',
                'verbose_name_plural': 'Add Calender Activity',
            },
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Public Disclosure',
                'verbose_name_plural': 'Add Public Disclosure',
            },
        ),
        migrations.CreateModel(
            name='Result_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Result Analysis',
                'verbose_name_plural': 'Add Result Analysis',
            },
        ),
        migrations.DeleteModel(
            name='class1',
        ),
        migrations.DeleteModel(
            name='class11',
        ),
        migrations.AlterField(
            model_name='committies',
            name='Committee_name',
            field=models.TextField(choices=[('Admissions', 'Admissions'), ('Academic Advisory', 'Academic Advisory'), ('Examination', 'Examination'), ('Transportation', 'Transportation'), ('Accommodation', 'Accommodation'), ('Guidance', 'Guidance'), ('Alumni', 'Alumni'), ('Suggestions', 'Suggestions'), ('Discipline', 'Discipline'), ('Computer Infrastructure', 'Computer Infrastructure')]),
        ),
        migrations.AlterField(
            model_name='news_and_events',
            name='title',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 23)),
        ),
    ]
