# Generated by Django 4.2.4 on 2023-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_affiliation_calender_of_activities_disclosure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Enrollment Statistics',
                'verbose_name_plural': 'Add Enrollment Statics',
            },
        ),
    ]
