# Generated by Django 4.2.4 on 2023-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers_achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='website/images')),
            ],
            options={
                'verbose_name': 'Add Teachers Achievement',
                'verbose_name_plural': 'Add Teachers Achievement',
            },
        ),
        migrations.CreateModel(
            name='Video_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=128)),
                ('link', models.TextField(max_length=128)),
            ],
        ),
    ]
