# Generated by Django 4.2.4 on 2023-08-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_teachers_achievement_video_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video_gallery',
            options={'verbose_name': 'Add Video Link', 'verbose_name_plural': 'Add Video Link'},
        ),
    ]
