# Generated by Django 4.2 on 2023-07-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='website/images')),
            ],
            options={
                'verbose_name': 'Add Achievement',
                'verbose_name_plural': 'Add Achievement',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description_of_acheivement', models.TextField(max_length=128)),
            ],
            options={
                'verbose_name': 'Add Alumni',
                'verbose_name_plural': 'Add Alumni',
            },
        ),
        migrations.CreateModel(
            name='Carousel_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='website/images/')),
                ('image_2', models.ImageField(upload_to='website/images/')),
                ('image_3', models.ImageField(upload_to='website/images/')),
                ('image_4', models.ImageField(upload_to='website/images/')),
            ],
            options={
                'verbose_name': 'Add Image to Caurosel',
                'verbose_name_plural': 'Add Image to Carousel',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Add Class in TC',
                'verbose_name_plural': 'Add Class in TC',
            },
        ),
        migrations.CreateModel(
            name='class1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add class 1 vacancy file',
                'verbose_name_plural': 'Add class 1 vacancy file',
            },
        ),
        migrations.CreateModel(
            name='class11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add class 11 vacancy file',
                'verbose_name_plural': 'Add class 11 vacancy file',
            },
        ),
        migrations.CreateModel(
            name='Fee_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Fee Structure',
                'verbose_name_plural': 'Add Fee Structure',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=None)),
                ('category', models.CharField(choices=[('holiday', 'Holiday'), ('summer_vacation', 'Summer Vacation'), ('winter_vacation', 'Winter Vacation'), ('autum_vacation', 'Autum Vacation')], max_length=32)),
            ],
            options={
                'verbose_name': 'Add Holiday',
                'verbose_name_plural': 'Add Holiday',
            },
        ),
        migrations.CreateModel(
            name='member_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('PGT (Physics)', 'PGT (Physics)'), ('PGT (Chemistry)', 'PGT (Chemistry)'), ('PGT (Maths)', 'PGT (Maths)'), ('PGT (Biology)', 'PGT (Biology)'), ('PGT (Computer)', 'PGT (Computer)'), ('PGT (Economics)', 'PGT (Economics)'), ('PGT (Commerce)', 'PGT (Commerce)'), ('PGT (English)', 'PGT (English)'), ('PGT (Hindi)', 'PGT (Hindi)'), ('TGT (Science)', 'TGT (Science)'), ('TGT (Maths)', 'TGT (Maths)'), ('TGT (Sanskrit)', 'TGT (Sanskrit)'), ('TGT (Social Science)', 'TGT (Social Science)'), ('TGT (English)', 'TGT (English)'), ('TGT (Hindi)', 'TGT (Hindi)'), ('PRT', 'PRT'), ('SSA', 'SSA'), ('Lab Attendant', 'Lab Attendant'), ('Sub Staff', 'Sub Staff'), ('JR. Secratariat Assistant', 'JR. Secratariat Assistant')], max_length=32)),
                ('origin', models.CharField(choices=[('Local', 'Local'), ('Indian', 'Indian')], max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/images/')),
            ],
            options={
                'verbose_name': 'Add Staff',
                'verbose_name_plural': 'Add Staff',
            },
        ),
        migrations.CreateModel(
            name='News_and_Events',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Add Event Item',
                'verbose_name_plural': 'Add Event Item',
            },
        ),
        migrations.CreateModel(
            name='News_letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Make News Letter Entry',
                'verbose_name_plural': 'Make News Letter Entry',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Add Notice',
                'verbose_name_plural': 'Add Notice',
            },
        ),
        migrations.CreateModel(
            name='principals_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='website/images/')),
            ],
            options={
                'verbose_name': 'Add  Principals message',
                'verbose_name_plural': 'Add Principals message',
            },
        ),
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('last_updated', models.DateField()),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('Student_Name', models.TextField(default=None, max_length=128)),
                ('Parent_Name', models.TextField(default=None, max_length=128)),
                ('Date_of_Birth', models.DateField(default=None)),
                ('Adm_No', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Class_Left', models.TextField(default=None)),
                ('Tc_No', models.PositiveBigIntegerField(default=None)),
                ('Date', models.DateField(default=None)),
            ],
            options={
                'verbose_name': 'Add Achievement',
                'verbose_name_plural': 'Add Achievement',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('vacant_designation', models.CharField(choices=[('principal', 'Principal'), ('PGT (Physics)', 'PGT (Physics)'), ('PGT (Chemistry)', 'PGT (Chemistry)'), ('PGT (Maths)', 'PGT (Maths)'), ('PGT (Biology)', 'PGT (Biology)'), ('PGT (Computer)', 'PGT (Computer)'), ('PGT (Economics)', 'PGT (Economics)'), ('PGT (Commerce)', 'PGT (Commerce)'), ('PGT (English)', 'PGT (English)'), ('PGT (Hindi)', 'PGT (Hindi)'), ('TGT (Science)', 'TGT (Science)'), ('TGT (Maths)', 'TGT (Maths)'), ('TGT (Sanskrit)', 'TGT (Sanskrit)'), ('TGT (Social Science)', 'TGT (Social Science)'), ('TGT (English)', 'TGT (English)'), ('TGT (Hindi)', 'TGT (Hindi)'), ('PRT', 'PRT'), ('SSA', 'SSA'), ('Lab Attendant', 'Lab Attendant'), ('Sub Staff', 'Sub Staff'), ('JR. Secratariat Assistant', 'JR. Secratariat Assistant')], max_length=32)),
            ],
            options={
                'verbose_name': 'Add Vacancy',
                'verbose_name_plural': 'Add Vacancy',
            },
        ),
        migrations.CreateModel(
            name='vmc_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('post', models.TextField()),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Add VMC member',
                'verbose_name_plural': 'Add VMC member',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/images/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.news_and_events')),
            ],
            options={
                'verbose_name': 'Add Image for event',
                'verbose_name_plural': 'Add Image for event',
            },
        ),
        migrations.CreateModel(
            name='Committies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_name', models.TextField(choices=[('Admissions', 'Admissions'), ('Academic advisory', 'Academic_Advisory'), ('Examination', 'Examination'), ('Transpotation', 'Transpotation')])),
                ('members', models.ManyToManyField(related_name='committees', to='main_app.member_list')),
            ],
            options={
                'verbose_name': 'Update Committee Member',
                'verbose_name_plural': 'Update Committee Member',
            },
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.IntegerField()),
                ('file', models.FileField(default=None, upload_to='website/files')),
                ('grade', models.ManyToManyField(related_name='vacancy_class', to='main_app.class')),
            ],
            options={
                'verbose_name': 'Vacancy for Other Classes',
                'verbose_name_plural': 'Vacancy for Other Classes',
            },
        ),
    ]
