# Generated by Django 4.2 on 2023-05-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('serial_number', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('parents_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('Admission_number', models.BigIntegerField()),
                ('TC_no', models.BigIntegerField(unique=True)),
                ('issue_date', models.DateField()),
                ('Class_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TCs_issued_by_class', to='main_app.classe')),
            ],
        ),
    ]
