# Generated by Django 4.2 on 2023-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_classe_tc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classe',
            new_name='Class',
        ),
        migrations.AlterField(
            model_name='tc',
            name='serial_number',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
