# Generated by Django 4.2 on 2023-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_academic_notice_administrative_notice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
        ),
    ]
