# Generated by Django 4.2 on 2023-06-05 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_fee_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='file',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='title',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
