# Generated by Django 4.2 on 2023-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_date_holiday_end_date_holiday_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.TextField(max_length=32),
        ),
    ]
