# Generated by Django 4.2 on 2023-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_holiday_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_Notice',
            new_name='News_and_Events',
        ),
        migrations.RenameModel(
            old_name='Administrative_Notice',
            new_name='Notice',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
