# Generated by Django 4.2 on 2023-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_academic_notice_news_and_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='website/images/')),
                ('image_2', models.ImageField(upload_to='website/images/')),
                ('image_3', models.ImageField(upload_to='website/images/')),
                ('image_4', models.ImageField(upload_to='website/images/')),
            ],
        ),
    ]
