# Generated by Django 4.2 on 2023-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_and_events',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
