# Generated by Django 4.2 on 2023-06-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_upload_images_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_and_Events',
        ),
    ]
