# Generated by Django 4.2 on 2023-06-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_news_and_events_file_alter_upload_images_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='news_and_events',
            name='file',
        ),
        migrations.DeleteModel(
            name='Upload_Images',
        ),
        migrations.AddField(
            model_name='images',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.news_and_events'),
        ),
    ]
