# Generated by Django 4.2 on 2023-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_images_remove_news_and_events_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_and_events',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
