# Generated by Django 4.2 on 2023-06-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_gallery_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_name', models.TextField(choices=[('admissions', 'Admissions'), ('academic_advisory', 'Academic_Advisory'), ('examination', 'Examination'), ('transpotation', 'Transpotation')])),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='main_app.member_list')),
            ],
        ),
    ]
