# Generated by Django 4.2 on 2023-06-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_committies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committies',
            name='members',
        ),
        migrations.AddField(
            model_name='committies',
            name='members',
            field=models.ManyToManyField(related_name='committees', to='main_app.member_list'),
        ),
    ]
