# Generated by Django 4.2 on 2023-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_committies_committee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='image',
        ),
        migrations.AlterField(
            model_name='vmc_member',
            name='post',
            field=models.TextField(),
        ),
    ]
