# Generated by Django 4.2 on 2023-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_alumni_image_alter_vmc_member_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'verbose_name': 'Add Alumni', 'verbose_name_plural': 'Add Alumni'},
        ),
        migrations.AlterModelOptions(
            name='carousel_image',
            options={'verbose_name': 'Add Image to Caurosel', 'verbose_name_plural': 'Add Image to Carousel'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Add Class in TC', 'verbose_name_plural': 'Add Class in TC'},
        ),
        migrations.AlterModelOptions(
            name='committies',
            options={'verbose_name': 'Update Committee Member', 'verbose_name_plural': 'Update Committee Member'},
        ),
        migrations.AlterModelOptions(
            name='fee_structure',
            options={'verbose_name': 'Add Fee Structure', 'verbose_name_plural': 'Add Fee Structure'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Add Gallery Item', 'verbose_name_plural': 'Add Gallery Item'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Add Holiday', 'verbose_name_plural': 'Add Holiday'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Add Image For gallery and event', 'verbose_name_plural': 'Add Image For gallery and event'},
        ),
        migrations.AlterModelOptions(
            name='member_list',
            options={'verbose_name': 'Add Staff', 'verbose_name_plural': 'Add Staff'},
        ),
        migrations.AlterModelOptions(
            name='news_and_events',
            options={'verbose_name': 'Add Event Item', 'verbose_name_plural': 'Add Event Item'},
        ),
        migrations.AlterModelOptions(
            name='news_letter',
            options={'verbose_name': 'Make News Letter Entry', 'verbose_name_plural': 'Make News Letter Entry'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Add Notice', 'verbose_name_plural': 'Add Notice'},
        ),
        migrations.AlterModelOptions(
            name='principals_message',
            options={'verbose_name': 'Add  Principals message', 'verbose_name_plural': 'Add Principals message'},
        ),
        migrations.AlterModelOptions(
            name='tc',
            options={'verbose_name': 'Add TC', 'verbose_name_plural': 'Add TC'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Add Vacancy', 'verbose_name_plural': 'Add Vacancy'},
        ),
        migrations.AlterModelOptions(
            name='vmc_member',
            options={'verbose_name': 'Add VMC member', 'verbose_name_plural': 'Add VMC member'},
        ),
        migrations.AddField(
            model_name='member_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/images/'),
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('grade', models.ManyToManyField(related_name='vacancy_class', to='main_app.class')),
            ],
        ),
    ]
