# Generated by Django 4.2 on 2023-06-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_alumni_options_alter_carousel_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions',
            options={'verbose_name': 'Vacancy for Other Classes', 'verbose_name_plural': 'Vacancy for Other Classes'},
        ),
        migrations.RenameField(
            model_name='admissions',
            old_name='number',
            new_name='vacancy',
        ),
    ]
