# Generated by Django 4.2 on 2023-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_admissions_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='class1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add admission ',
                'verbose_name_plural': 'Add Fee Structure',
            },
        ),
        migrations.CreateModel(
            name='class11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/files')),
            ],
            options={
                'verbose_name': 'Add Fee Structure',
                'verbose_name_plural': 'Add Fee Structure',
            },
        ),
    ]
