# Generated by Django 4.2 on 2023-06-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_remove_images_gallery_delete_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Add Image for event', 'verbose_name_plural': 'Add Image for event'},
        ),
    ]
