# Generated by Django 4.2 on 2023-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_alter_images_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='website/images')),
            ],
            options={
                'verbose_name': 'Add Achievement',
                'verbose_name_plural': 'Add Achievement',
            },
        ),
        migrations.AlterModelOptions(
            name='class1',
            options={'verbose_name': 'Add class 1 vacancy file', 'verbose_name_plural': 'Add class 1 vacancy file'},
        ),
        migrations.AlterModelOptions(
            name='class11',
            options={'verbose_name': 'Add class 11 vacancy file', 'verbose_name_plural': 'Add class 11 vacancy file'},
        ),
    ]
