# Generated by Django 4.2 on 2023-07-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_achievement_alter_class1_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
